---
http_interactions:
- request:
    method: post
    uri: http://api.brightbox.localhost/token
    body:
      encoding: UTF-8
      string: '{"grant_type":"password","username":"jason.null@brightbox.com","password":"N:B3e%7Cmh"}'
    headers:
      User-Agent:
      - fog/1.15.0
      Authorization:
      - Basic YXBwLTEyMzQ1Om1vY2J1aXBiaWFhNms2Yw==
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message:
    headers:
      X-Frame-Options:
      - sameorigin
      X-XSS-Protection:
      - 1; mode=block
      Content-Type:
      - application/json;charset=utf-8
      Cache-Control:
      - no-store
      Content-Length:
      - '136'
      X-UA-Compatible:
      - IE=Edge
      ETag:
      - '"e221095ab343b006469ba6fe150d5113"'
      X-Request-Id:
      - d02cbd1cf753a63af1bf4e836e06ced8
      X-Runtime:
      - '2.073946'
      Date:
      - Fri, 06 Sep 2013 10:19:09 GMT
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"access_token":"9f30697244cb53c782c7a6af95259d212ede132b","expires_in":7200,"refresh_token":"305ae4a60568a02d606744372dc7b8a2b80d7a8e"}'
    http_version:
  recorded_at: Fri, 06 Sep 2013 10:19:09 GMT
- request:
    method: get
    uri: http://api.brightbox.localhost/1.0/accounts
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - fog/1.15.0
      Authorization:
      - OAuth f7d882463fb3e652703d09227a2368e6e83812a7
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message:
    headers:
      Content-Type:
      - application/json; charset=utf-8
      X-UA-Compatible:
      - IE=Edge
      ETag:
      - '"d40ca0ee4b8bedc3d493e1c7674a861e"'
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - b3a9beef81ac5d04321ac7fd76df5843
      X-Runtime:
      - '12.387151'
      Date:
      - Fri, 06 Sep 2013 10:19:22 GMT
      Connection:
      - close
    body:
      encoding: UTF-8
      string: '[{"id":"acc-11111","resource_type":"account","url":"https://api.gb1.brightbox.com/1.0/accounts/acc-11111","name":"Aurnqfvgsbeyiprni","status":"closed","ram_limit":32768,"ram_used":0,"cloud_ips_limit":20,"cloud_ips_used":1,"load_balancers_limit":5,"load_balancers_used":0,"clients":[{"id":"cli-12345","resource_type":"api_client","url":"https://api.gb1.brightbox.com/1.0/api_clients/cli-12345","name":null,"description":null,"revoked_at":null}],"images":[],"servers":[],"load_balancers":[],"cloud_ips":[{"id":"cip-12345","resource_type":"cloud_ip","url":"https://api.gb1.brightbox.com/1.0/cloud_ips/cip-12345","status":"unmapped","public_ip":"56.67.59.219","reverse_dns":"cip-12345-67-59-219.gb1.brightbox.com","name":null}],"server_groups":[{"id":"grp-12345","resource_type":"server_group","url":"https://api.gb1.brightbox.com/1.0/server_groups/grp-12345","name":"default","description":"All
        new servers are added to this group unless specified otherwise.","created_at":"2013-09-04T07:53:13Z","default":true}],"firewall_policies":[{"id":"fwp-12345","resource_type":"firewall_policy","url":"https://api.gb1.brightbox.com/1.0/firewall_policies/fwp-12345","default":true,"name":"default","created_at":"2013-09-04T07:53:14Z","description":"Applied
        to the default server group."}],"owner":{"id":"usr-12345","resource_type":"user","url":"https://api.gb1.brightbox.com/1.0/users/usr-12345","name":"Dylan
        Fay DDS","email_address":"jason.null@brightbox.com"},"users":[],"zones":[{"id":"zon-12345","resource_type":"zone","url":"https://api.gb1.brightbox.com/1.0/zones/zon-12345","handle":"gb1-a"},{"id":"zon-12345","resource_type":"zone","url":"https://api.gb1.brightbox.com/1.0/zones/zon-12345","handle":"gb1-b"}]},
        {"id":"acc-22222","resource_type":"account","url":"https://api.gb1.brightbox.com/1.0/accounts/acc-22222","name":"Aurnqfvgsbeyiprni","status":"deleted","ram_limit":32768,"ram_used":0,"cloud_ips_limit":20,"cloud_ips_used":1,"load_balancers_limit":5,"load_balancers_used":0,"clients":[{"id":"cli-12345","resource_type":"api_client","url":"https://api.gb1.brightbox.com/1.0/api_clients/cli-12345","name":null,"description":null,"revoked_at":null}],"images":[],"servers":[],"load_balancers":[],"cloud_ips":[{"id":"cip-12345","resource_type":"cloud_ip","url":"https://api.gb1.brightbox.com/1.0/cloud_ips/cip-12345","status":"unmapped","public_ip":"56.67.59.219","reverse_dns":"cip-12345-67-59-219.gb1.brightbox.com","name":null}],"server_groups":[{"id":"grp-12345","resource_type":"server_group","url":"https://api.gb1.brightbox.com/1.0/server_groups/grp-12345","name":"default","description":"All
        new servers are added to this group unless specified otherwise.","created_at":"2013-09-04T07:53:13Z","default":true}],"firewall_policies":[{"id":"fwp-12345","resource_type":"firewall_policy","url":"https://api.gb1.brightbox.com/1.0/firewall_policies/fwp-12345","default":true,"name":"default","created_at":"2013-09-04T07:53:14Z","description":"Applied
        to the default server group."}],"owner":{"id":"usr-12345","resource_type":"user","url":"https://api.gb1.brightbox.com/1.0/users/usr-12345","name":"Dylan
        Fay DDS","email_address":"jason.null@brightbox.com"},"users":[],"zones":[{"id":"zon-12345","resource_type":"zone","url":"https://api.gb1.brightbox.com/1.0/zones/zon-12345","handle":"gb1-a"},{"id":"zon-12345","resource_type":"zone","url":"https://api.gb1.brightbox.com/1.0/zones/zon-12345","handle":"gb1-b"}]},
        {"id":"acc-33333","resource_type":"account","url":"https://api.gb1.brightbox.com/1.0/accounts/acc-33333","name":"Aurnqfvgsbeyiprni","status":"active","ram_limit":32768,"ram_used":0,"cloud_ips_limit":20,"cloud_ips_used":1,"load_balancers_limit":5,"load_balancers_used":0,"clients":[{"id":"cli-12345","resource_type":"api_client","url":"https://api.gb1.brightbox.com/1.0/api_clients/cli-12345","name":null,"description":null,"revoked_at":null}],"images":[],"servers":[],"load_balancers":[],"cloud_ips":[{"id":"cip-12345","resource_type":"cloud_ip","url":"https://api.gb1.brightbox.com/1.0/cloud_ips/cip-12345","status":"unmapped","public_ip":"56.67.59.219","reverse_dns":"cip-12345-67-59-219.gb1.brightbox.com","name":null}],"server_groups":[{"id":"grp-12345","resource_type":"server_group","url":"https://api.gb1.brightbox.com/1.0/server_groups/grp-12345","name":"default","description":"All
        new servers are added to this group unless specified otherwise.","created_at":"2013-09-04T07:53:13Z","default":true}],"firewall_policies":[{"id":"fwp-12345","resource_type":"firewall_policy","url":"https://api.gb1.brightbox.com/1.0/firewall_policies/fwp-12345","default":true,"name":"default","created_at":"2013-09-04T07:53:14Z","description":"Applied
        to the default server group."}],"owner":{"id":"usr-12345","resource_type":"user","url":"https://api.gb1.brightbox.com/1.0/users/usr-12345","name":"Dylan
        Fay DDS","email_address":"jason.null@brightbox.com"},"users":[],"zones":[{"id":"zon-12345","resource_type":"zone","url":"https://api.gb1.brightbox.com/1.0/zones/zon-12345","handle":"gb1-a"},{"id":"zon-12345","resource_type":"zone","url":"https://api.gb1.brightbox.com/1.0/zones/zon-12345","handle":"gb1-b"}]}]'
    http_version:
  recorded_at: Fri, 06 Sep 2013 10:19:22 GMT
recorded_with: VCR 2.5.0
