---
http_interactions:
- request:
    method: post
    uri: http://api.brightbox.localhost/token
    body:
      encoding: UTF-8
      string: '{"grant_type":"password","username":"jason.null@brightbox.com","password":"N:B3e%7Cmh"}'
    headers:
      User-Agent:
      - fog-core/1.32.1
      Authorization:
      - Basic YXBwLTEyMzQ1Om1vY2J1aXBiaWFhNms2Yw==
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message:
    headers:
      Content-Type:
      - application/json
      Cache-Control:
      - no-store
      X-Oauth-Scopes:
      - infrastructure, orbit
      Content-Length:
      - '190'
      X-Content-Type-Options:
      - nosniff
      X-Ua-Compatible:
      - IE=Edge
      Etag:
      - '"52cf652e4c8197b06a5df541b6c6e6b6"'
      X-Request-Id:
      - c41fe56cfea4d84c928af11c4ad27b60
      X-Runtime:
      - '0.086987'
      Server:
      - WEBrick/1.3.1 (Ruby/1.9.3/2014-11-13)
      Date:
      - Mon, 12 Oct 2015 11:34:18 GMT
      Connection:
      - Keep-Alive
    body:
      encoding: UTF-8
      string: '{"access_token":"cd64dd737e020f9975a97c35e78e27e46442eb27","token_type":"Bearer","refresh_token":"00114bd8f6aa955911870efbb5f8b135dc6fc9c5","scope":"infrastructure,
        orbit","expires_in":7200}'
    http_version:
  recorded_at: Mon, 12 Oct 2015 11:34:18 GMT
- request:
    method: get
    uri: http://api.brightbox.localhost/1.0/accounts
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - fog-core/1.32.1
      Authorization:
      - Bearer cd64dd737e020f9975a97c35e78e27e46442eb27
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message:
    headers:
      X-Oauth-Scopes:
      - infrastructure, orbit
      Content-Type:
      - application/json; charset=utf-8
      X-Ua-Compatible:
      - IE=Edge
      Etag:
      - '"c9a269456e92ca15ff834e08ba6414ad"'
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - f4dde3adcaecea5e4df8f56927b328b5
      X-Runtime:
      - '0.044869'
      Server:
      - WEBrick/1.3.1 (Ruby/1.9.3/2014-11-13)
      Date:
      - Mon, 12 Oct 2015 11:34:18 GMT
      Content-Length:
      - '1611'
      Connection:
      - Keep-Alive
    body:
      encoding: UTF-8
      string: '[{"id":"acc-12345","resource_type":"account","url":"https://api.gb1.brightbox.com/1.0/accounts/acc-12345","name":"CLI
        test account","status":"active","ram_limit":3200000,"ram_used":0,"dbs_ram_limit":32768,"dbs_ram_used":0,"cloud_ips_limit":32,"cloud_ips_used":0,"load_balancers_limit":5,"load_balancers_used":0,"clients":[{"id":"cli-12345","resource_type":"api_client","url":"https://api.gb1.brightbox.com/1.0/api_clients/cli-12345","name":"CLI
        test API client","description":"","revoked_at":null,"permissions_group":"full"}],"images":[],"servers":[],"load_balancers":[],"database_servers":[],"database_snapshots":[],"cloud_ips":[],"server_groups":[{"id":"grp-12345","resource_type":"server_group","url":"https://api.gb1.brightbox.com/1.0/server_groups/grp-12345","name":"default","description":"All
        new servers are added to this group unless specified otherwise.","created_at":"2015-10-12T09:23:03Z","default":true}],"firewall_policies":[{"id":"fwp-12345","resource_type":"firewall_policy","url":"https://api.gb1.brightbox.com/1.0/firewall_policies/fwp-12345","default":true,"name":"default","created_at":"2015-10-12T09:23:03Z","description":"Applied
        to the default server group."}],"owner":{"id":"usr-12345","resource_type":"user","url":"https://api.gb1.brightbox.com/1.0/users/usr-12345","name":"Jason
        Null","email_address":"jason.null@brightbox.com"},"users":[],"zones":[{"id":"zon-12345","resource_type":"zone","url":"https://api.gb1.brightbox.com/1.0/zones/zon-12345","handle":"gb1-a"},{"id":"zon-12345","resource_type":"zone","url":"https://api.gb1.brightbox.com/1.0/zones/zon-12345","handle":"gb1-b"}]}]'
    http_version:
  recorded_at: Mon, 12 Oct 2015 11:34:18 GMT
recorded_with: VCR 2.5.0
